### ISSUE TITLE
base project for mobile apps

### ISSUE THREAD

**Issue by IzumiShaka-desu** [chuck1z/capstone-project#1]
this todo assigned to @IzumiShaka-desu  😙
## TODOS
- [x] create an initial base project
- [x] configure Dependency Injection
- [x] configure project structure
- [x] configure base network module
- [x] configure base navigation
- [x] configure app icon
- [x] configure splash screen

**Comment by IzumiShaka-desu** [comment]
currently configuring splash screen

**Comment by IzumiShaka-desu** [comment]
currently create readme documentation
