### ISSUE TITLE
3rd iteration todo #1

### ISSUE THREAD

**Issue by IzumiShaka-desu** [chuck1z/capstone-project#10]
this todo assigned to @Sitifatimah121 
## TODOS
- [x] implement get fruits of the day on datasource 
- [x] implement get tips on datasource 
- [x] create tips detail(UI)
