### ISSUE TITLE
 3rd iteration todo #2

### ISSUE THREAD

**Issue by IzumiShaka-desu** [chuck1z/capstone-project#12]
this todo assigned to @IzumiShaka-desu 
## TODOS
- [x] implement e2e history feature
- [x] implement add guide feature
- [x] implement one time setup
