### ISSUE TITLE
first iteration todo #2

### ISSUE THREAD

**Issue by IzumiShaka-desu** [chuck1z/capstone-project#4]
this todo assigned to @Sitifatimah121 
## TODOS
- [x] slicing ui from figma into home fruits page
- [x] slicing ui from figma into detail fruits page
- [x] make adjustments on activity main UI
