### ISSUE TITLE
2nd iteration todo #2 

### ISSUE THREAD

**Issue by IzumiShaka-desu** [chuck1z/capstone-project#7]
this todo assigned to @Sitifatimah121  
## TODOS
- [x] slicing ui from figma into setting page
- [x] slicing ui from figma into history page
- [x] slicing ui from figma into about page
