### ISSUE TITLE
2nd iteration todo #1

### ISSUE THREAD

**Issue by IzumiShaka-desu** [chuck1z/capstone-project#8]
this todo assigned to @IzumiShaka-desu  
## TODOS
- [x] implement get detail fruits feature on datasource (dummy)
- [x] implement get latest model feature on datasource (dummy)
- [x] implement classifier feature on datasource(dumyy)
